// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package server

import (
	"context"

	"user-rpc/internal/logic"
	"user-rpc/internal/svc"
	"user-rpc/pb/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetProfile(ctx context.Context, in *user.Empty) (*user.ProfileResponse, error) {
	l := logic.NewGetProfileLogic(ctx, s.svcCtx)
	return l.GetProfile(in)
}

func (s *UserServer) GetMe(ctx context.Context, in *user.GetMeRequest) (*user.UserResponse, error) {
	l := logic.NewGetMeLogic(ctx, s.svcCtx)
	return l.GetMe(in)
}

func (s *UserServer) UpdateProfile(ctx context.Context, in *user.UpdateProfileRequest) (*user.EmptyResponse, error) {
	l := logic.NewUpdateProfileLogic(ctx, s.svcCtx)
	return l.UpdateProfile(in)
}

func (s *UserServer) UpdatePassword(ctx context.Context, in *user.UpdatePasswordRequest) (*user.EmptyResponse, error) {
	l := logic.NewUpdatePasswordLogic(ctx, s.svcCtx)
	return l.UpdatePassword(in)
}
