// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: blog.proto

package server

import (
	"context"

	"blog-rpc/internal/logic"
	"blog-rpc/internal/svc"
	"blog-rpc/pb/blog"
)

type BlogServer struct {
	svcCtx *svc.ServiceContext
	blog.UnimplementedBlogServer
}

func NewBlogServer(svcCtx *svc.ServiceContext) *BlogServer {
	return &BlogServer{
		svcCtx: svcCtx,
	}
}

func (s *BlogServer) CreatePost(ctx context.Context, in *blog.CreatePostRequest) (*blog.CreatePostResponse, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *BlogServer) GetPost(ctx context.Context, in *blog.GetPostRequest) (*blog.GetPostResponse, error) {
	l := logic.NewGetPostLogic(ctx, s.svcCtx)
	return l.GetPost(in)
}

func (s *BlogServer) ListPosts(ctx context.Context, in *blog.ListPostsRequest) (*blog.ListPostsResponse, error) {
	l := logic.NewListPostsLogic(ctx, s.svcCtx)
	return l.ListPosts(in)
}

func (s *BlogServer) UpdatePost(ctx context.Context, in *blog.UpdatePostRequest) (*blog.UpdatePostResponse, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

func (s *BlogServer) DeletePost(ctx context.Context, in *blog.DeletePostRequest) (*blog.DeletePostResponse, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}
