// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: blog.proto

package server

import (
	"context"

	"blog-rpc/internal/logic"
	"blog-rpc/internal/svc"
	"blog-rpc/pb/blog"
)

type BlogServer struct {
	svcCtx *svc.ServiceContext
	blog.UnimplementedBlogServer
}

func NewBlogServer(svcCtx *svc.ServiceContext) *BlogServer {
	return &BlogServer{
		svcCtx: svcCtx,
	}
}

func (s *BlogServer) ListPublicPosts(ctx context.Context, in *blog.ListPostsRequest) (*blog.ListPublicPostsResponse, error) {
	l := logic.NewListPublicPostsLogic(ctx, s.svcCtx)
	return l.ListPublicPosts(in)
}

func (s *BlogServer) GetPublicPost(ctx context.Context, in *blog.GetPostRequest) (*blog.PublicPostResponse, error) {
	l := logic.NewGetPublicPostLogic(ctx, s.svcCtx)
	return l.GetPublicPost(in)
}

func (s *BlogServer) ListCategories(ctx context.Context, in *blog.Empty) (*blog.ListCategoriesResponse, error) {
	l := logic.NewListCategoriesLogic(ctx, s.svcCtx)
	return l.ListCategories(in)
}

func (s *BlogServer) ListAdminPosts(ctx context.Context, in *blog.ListPostsRequest) (*blog.ListAdminPostsResponse, error) {
	l := logic.NewListAdminPostsLogic(ctx, s.svcCtx)
	return l.ListAdminPosts(in)
}

func (s *BlogServer) GetAdminPost(ctx context.Context, in *blog.GetPostRequest) (*blog.AdminPostResponse, error) {
	l := logic.NewGetAdminPostLogic(ctx, s.svcCtx)
	return l.GetAdminPost(in)
}

func (s *BlogServer) CreatePost(ctx context.Context, in *blog.CreatePostRequest) (*blog.CreatePostResponse, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *BlogServer) UpdatePost(ctx context.Context, in *blog.UpdatePostRequest) (*blog.EmptyResponse, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

func (s *BlogServer) DeletePost(ctx context.Context, in *blog.DeletePostRequest) (*blog.EmptyResponse, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

func (s *BlogServer) CreateCategory(ctx context.Context, in *blog.CreateCategoryRequest) (*blog.CreateCategoryResponse, error) {
	l := logic.NewCreateCategoryLogic(ctx, s.svcCtx)
	return l.CreateCategory(in)
}

func (s *BlogServer) UpdateCategory(ctx context.Context, in *blog.UpdateCategoryRequest) (*blog.EmptyResponse, error) {
	l := logic.NewUpdateCategoryLogic(ctx, s.svcCtx)
	return l.UpdateCategory(in)
}

func (s *BlogServer) DeleteCategory(ctx context.Context, in *blog.DeleteCategoryRequest) (*blog.EmptyResponse, error) {
	l := logic.NewDeleteCategoryLogic(ctx, s.svcCtx)
	return l.DeleteCategory(in)
}

func (s *BlogServer) UploadImage(ctx context.Context, in *blog.UploadImageRequest) (*blog.UploadImageResponse, error) {
	l := logic.NewUploadImageLogic(ctx, s.svcCtx)
	return l.UploadImage(in)
}
