// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package userclient

import (
	"context"

	"user-rpc/pb/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty                 = user.Empty
	EmptyResponse         = user.EmptyResponse
	GetMeRequest          = user.GetMeRequest
	LoginRequest          = user.LoginRequest
	LoginResponse         = user.LoginResponse
	ProfileResponse       = user.ProfileResponse
	UpdatePasswordRequest = user.UpdatePasswordRequest
	UpdateProfileRequest  = user.UpdateProfileRequest
	UserResponse          = user.UserResponse

	User interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		GetProfile(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProfileResponse, error)
		GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*UserResponse, error)
		UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) GetProfile(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProfileResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetProfile(ctx, in, opts...)
}

func (m *defaultUser) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetMe(ctx, in, opts...)
}

func (m *defaultUser) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateProfile(ctx, in, opts...)
}

func (m *defaultUser) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdatePassword(ctx, in, opts...)
}
