// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	categoriesFieldNames          = builder.RawFieldNames(&Categories{}, true)
	categoriesRows                = strings.Join(categoriesFieldNames, ",")
	categoriesRowsExpectAutoSet   = strings.Join(stringx.Remove(categoriesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	categoriesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(categoriesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicCategoriesIdPrefix   = "cache:public:categories:id:"
	cachePublicCategoriesNamePrefix = "cache:public:categories:name:"
	cachePublicCategoriesSlugPrefix = "cache:public:categories:slug:"
)

type (
	categoriesModel interface {
		Insert(ctx context.Context, data *Categories) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Categories, error)
		FindOneByName(ctx context.Context, name string) (*Categories, error)
		FindOneBySlug(ctx context.Context, slug string) (*Categories, error)
		Update(ctx context.Context, data *Categories) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCategoriesModel struct {
		sqlc.CachedConn
		table string
	}

	Categories struct {
		Id        int64     `db:"id"`
		Name      string    `db:"name"`
		Slug      string    `db:"slug"`
		Sort      int64     `db:"sort"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newCategoriesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCategoriesModel {
	return &defaultCategoriesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."categories"`,
	}
}

func (m *defaultCategoriesModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicCategoriesIdKey := fmt.Sprintf("%s%v", cachePublicCategoriesIdPrefix, id)
	publicCategoriesNameKey := fmt.Sprintf("%s%v", cachePublicCategoriesNamePrefix, data.Name)
	publicCategoriesSlugKey := fmt.Sprintf("%s%v", cachePublicCategoriesSlugPrefix, data.Slug)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicCategoriesIdKey, publicCategoriesNameKey, publicCategoriesSlugKey)
	return err
}

func (m *defaultCategoriesModel) FindOne(ctx context.Context, id int64) (*Categories, error) {
	publicCategoriesIdKey := fmt.Sprintf("%s%v", cachePublicCategoriesIdPrefix, id)
	var resp Categories
	err := m.QueryRowCtx(ctx, &resp, publicCategoriesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", categoriesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoriesModel) FindOneByName(ctx context.Context, name string) (*Categories, error) {
	publicCategoriesNameKey := fmt.Sprintf("%s%v", cachePublicCategoriesNamePrefix, name)
	var resp Categories
	err := m.QueryRowIndexCtx(ctx, &resp, publicCategoriesNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where name = $1 limit 1", categoriesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoriesModel) FindOneBySlug(ctx context.Context, slug string) (*Categories, error) {
	publicCategoriesSlugKey := fmt.Sprintf("%s%v", cachePublicCategoriesSlugPrefix, slug)
	var resp Categories
	err := m.QueryRowIndexCtx(ctx, &resp, publicCategoriesSlugKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where slug = $1 limit 1", categoriesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, slug); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoriesModel) Insert(ctx context.Context, data *Categories) (sql.Result, error) {
	publicCategoriesIdKey := fmt.Sprintf("%s%v", cachePublicCategoriesIdPrefix, data.Id)
	publicCategoriesNameKey := fmt.Sprintf("%s%v", cachePublicCategoriesNamePrefix, data.Name)
	publicCategoriesSlugKey := fmt.Sprintf("%s%v", cachePublicCategoriesSlugPrefix, data.Slug)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, categoriesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Slug, data.Sort)
	}, publicCategoriesIdKey, publicCategoriesNameKey, publicCategoriesSlugKey)
	return ret, err
}

func (m *defaultCategoriesModel) Update(ctx context.Context, newData *Categories) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicCategoriesIdKey := fmt.Sprintf("%s%v", cachePublicCategoriesIdPrefix, data.Id)
	publicCategoriesNameKey := fmt.Sprintf("%s%v", cachePublicCategoriesNamePrefix, data.Name)
	publicCategoriesSlugKey := fmt.Sprintf("%s%v", cachePublicCategoriesSlugPrefix, data.Slug)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, categoriesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.Name, newData.Slug, newData.Sort)
	}, publicCategoriesIdKey, publicCategoriesNameKey, publicCategoriesSlugKey)
	return err
}

func (m *defaultCategoriesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicCategoriesIdPrefix, primary)
}

func (m *defaultCategoriesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", categoriesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCategoriesModel) tableName() string {
	return m.table
}
