// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postsFieldNames          = builder.RawFieldNames(&Posts{}, true)
	postsRows                = strings.Join(postsFieldNames, ",")
	postsRowsExpectAutoSet   = strings.Join(stringx.Remove(postsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	postsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(postsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicPostsIdPrefix   = "cache:public:posts:id:"
	cachePublicPostsSlugPrefix = "cache:public:posts:slug:"
)

type (
	postsModel interface {
		Insert(ctx context.Context, data *Posts) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Posts, error)
		FindOneBySlug(ctx context.Context, slug string) (*Posts, error)
		Update(ctx context.Context, data *Posts) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPostsModel struct {
		sqlc.CachedConn
		table string
	}

	Posts struct {
		Id          int64         `db:"id"`
		UserId      int64         `db:"user_id"`
		CategoryId  sql.NullInt64 `db:"category_id"`
		Title       string        `db:"title"`
		Slug        string        `db:"slug"`
		Summary     string        `db:"summary"`
		Content     string        `db:"content"`
		Cover       string        `db:"cover"`
		Status      string        `db:"status"`
		ViewCount   int64         `db:"view_count"`
		PublishedAt sql.NullTime  `db:"published_at"`
		DeletedAt   sql.NullTime  `db:"deleted_at"`
		CreatedAt   time.Time     `db:"created_at"`
		UpdatedAt   time.Time     `db:"updated_at"`
	}
)

func newPostsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPostsModel {
	return &defaultPostsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."posts"`,
	}
}

func (m *defaultPostsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicPostsIdKey := fmt.Sprintf("%s%v", cachePublicPostsIdPrefix, id)
	publicPostsSlugKey := fmt.Sprintf("%s%v", cachePublicPostsSlugPrefix, data.Slug)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicPostsIdKey, publicPostsSlugKey)
	return err
}

func (m *defaultPostsModel) FindOne(ctx context.Context, id int64) (*Posts, error) {
	publicPostsIdKey := fmt.Sprintf("%s%v", cachePublicPostsIdPrefix, id)
	var resp Posts
	err := m.QueryRowCtx(ctx, &resp, publicPostsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", postsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostsModel) FindOneBySlug(ctx context.Context, slug string) (*Posts, error) {
	publicPostsSlugKey := fmt.Sprintf("%s%v", cachePublicPostsSlugPrefix, slug)
	var resp Posts
	err := m.QueryRowIndexCtx(ctx, &resp, publicPostsSlugKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where slug = $1 limit 1", postsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, slug); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostsModel) Insert(ctx context.Context, data *Posts) (sql.Result, error) {
	publicPostsIdKey := fmt.Sprintf("%s%v", cachePublicPostsIdPrefix, data.Id)
	publicPostsSlugKey := fmt.Sprintf("%s%v", cachePublicPostsSlugPrefix, data.Slug)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)", m.table, postsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.CategoryId, data.Title, data.Slug, data.Summary, data.Content, data.Cover, data.Status, data.ViewCount, data.PublishedAt, data.DeletedAt)
	}, publicPostsIdKey, publicPostsSlugKey)
	return ret, err
}

func (m *defaultPostsModel) Update(ctx context.Context, newData *Posts) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicPostsIdKey := fmt.Sprintf("%s%v", cachePublicPostsIdPrefix, data.Id)
	publicPostsSlugKey := fmt.Sprintf("%s%v", cachePublicPostsSlugPrefix, data.Slug)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, postsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.CategoryId, newData.Title, newData.Slug, newData.Summary, newData.Content, newData.Cover, newData.Status, newData.ViewCount, newData.PublishedAt, newData.DeletedAt)
	}, publicPostsIdKey, publicPostsSlugKey)
	return err
}

func (m *defaultPostsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicPostsIdPrefix, primary)
}

func (m *defaultPostsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", postsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPostsModel) tableName() string {
	return m.table
}
