// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type AdminPostItem struct {
	Id           int64  `json:"id"`           // 资源 ID
	Title        string `json:"title"`        // 文章标题
	Slug         string `json:"slug"`         // 文章别名
	Summary      string `json:"summary"`      // 文章摘要
	Cover        string `json:"cover"`        // 封面图片地址
	Status       string `json:"status"`       // 文章状态
	CategoryId   int64  `json:"categoryId"`   // 分类 ID
	CategoryName string `json:"categoryName"` // 分类名称
	ViewCount    int64  `json:"viewCount"`    // 浏览次数
	PublishedAt  int64  `json:"publishedAt"`  // 发布时间
	CreatedAt    int64  `json:"createdAt"`    // 创建时间
	UpdatedAt    int64  `json:"updatedAt"`    // 最后更新时间
}

type AdminPostResponse struct {
	Id           int64  `json:"id"`           // 资源 ID
	Title        string `json:"title"`        // 文章标题
	Slug         string `json:"slug"`         // 文章别名
	Summary      string `json:"summary"`      // 文章摘要
	Content      string `json:"content"`      // 文章正文
	Cover        string `json:"cover"`        // 封面图片地址
	Status       string `json:"status"`       // 文章状态
	CategoryId   int64  `json:"categoryId"`   // 分类 ID
	CategoryName string `json:"categoryName"` // 分类名称
	ViewCount    int64  `json:"viewCount"`    // 浏览次数
	PublishedAt  int64  `json:"publishedAt"`  // 发布时间
	CreatedAt    int64  `json:"createdAt"`    // 创建时间
	UpdatedAt    int64  `json:"updatedAt"`    // 最后更新时间
}

type CategoryItem struct {
	Id        int64  `json:"id"`        // 资源 ID
	Name      string `json:"name"`      // 分类名称
	Slug      string `json:"slug"`      // 分类别名
	Sort      int64  `json:"sort"`      // 分类排序值
	CreatedAt int64  `json:"createdAt"` // 创建时间
	UpdatedAt int64  `json:"updatedAt"` // 最后更新时间
}

type CreateCategoryRequest struct {
	Name string `json:"name"` // 分类名称
	Slug string `json:"slug"` // 分类别名
	Sort int64  `json:"sort"` // 分类排序值
}

type CreateCategoryResponse struct {
	Id int64 `json:"id"` // 资源 ID
}

type CreatePostRequest struct {
	Title       string `json:"title"`                // 文章标题
	Slug        string `json:"slug"`                 // 文章别名
	Summary     string `json:"summary"`              // 文章摘要
	Content     string `json:"content"`              // 文章正文
	Cover       string `json:"cover"`                // 封面图片地址
	Status      string `json:"status"`               // 文章状态
	CategoryId  int64  `json:"categoryId"`           // 分类 ID
	PublishedAt int64  `json:"publishedAt,optional"` // 发布时间
}

type CreatePostResponse struct {
	Id int64 `json:"id"` // 资源 ID
}

type DeleteCategoryRequest struct {
	Id int64 `path:"id"` // 资源 ID
}

type DeletePostRequest struct {
	Id int64 `path:"id"` // 资源 ID
}

type EmptyResponse struct {
}

type GetPostRequest struct {
	Id int64 `path:"id"` // 资源 ID
}

type ListAdminPostsResponse struct {
	Total int64           `json:"total"` // 数据总数
	Posts []AdminPostItem `json:"posts"` // 文章列表
}

type ListCategoriesResponse struct {
	Categories []CategoryItem `json:"categories"` // 分类列表
}

type ListPostsRequest struct {
	Page     int64  `json:"page,default=1"`      // 页码
	PageSize int64  `json:"pageSize,default=10"` // 每页数量
	Category string `json:"category,optional"`   // 分类筛选条件
	Keyword  string `json:"keyword,optional"`    // 关键词筛选条件
}

type ListPublicPostsResponse struct {
	Total int64            `json:"total"` // 数据总数
	Posts []PublicPostItem `json:"posts"` // 文章列表
}

type LoginRequest struct {
	Username string `json:"username"` // 登录用户名
	Password string `json:"password"` // 登录密码
}

type LoginResponse struct {
	Token     string `json:"token"`     // 访问令牌
	ExpiresAt int64  `json:"expiresAt"` // 令牌过期时间
}

type ProfileResponse struct {
	Id          int64  `json:"id"`          // 资源 ID
	Username    string `json:"username"`    // 登录用户名
	DisplayName string `json:"displayName"` // 显示名称
	Avatar      string `json:"avatar"`      // 头像地址
	Bio         string `json:"bio"`         // 个人简介
	Email       string `json:"email"`       // 邮箱地址
	Website     string `json:"website"`     // 个人网站地址
	Github      string `json:"github"`      // GitHub 主页地址
}

type PublicPostItem struct {
	Id           int64  `json:"id"`           // 资源 ID
	Title        string `json:"title"`        // 文章标题
	Slug         string `json:"slug"`         // 文章别名
	Summary      string `json:"summary"`      // 文章摘要
	Cover        string `json:"cover"`        // 封面图片地址
	CategoryId   int64  `json:"categoryId"`   // 分类 ID
	CategoryName string `json:"categoryName"` // 分类名称
	PublishedAt  int64  `json:"publishedAt"`  // 发布时间
	CreatedAt    int64  `json:"createdAt"`    // 创建时间
	UpdatedAt    int64  `json:"updatedAt"`    // 最后更新时间
}

type PublicPostResponse struct {
	Id           int64  `json:"id"`           // 资源 ID
	Title        string `json:"title"`        // 文章标题
	Slug         string `json:"slug"`         // 文章别名
	Summary      string `json:"summary"`      // 文章摘要
	Content      string `json:"content"`      // 文章正文
	Cover        string `json:"cover"`        // 封面图片地址
	CategoryId   int64  `json:"categoryId"`   // 分类 ID
	CategoryName string `json:"categoryName"` // 分类名称
	PublishedAt  int64  `json:"publishedAt"`  // 发布时间
	CreatedAt    int64  `json:"createdAt"`    // 创建时间
	UpdatedAt    int64  `json:"updatedAt"`    // 最后更新时间
}

type UpdateCategoryRequest struct {
	Id   int64  `path:"id"`   // 资源 ID
	Name string `json:"name"` // 分类名称
	Slug string `json:"slug"` // 分类别名
	Sort int64  `json:"sort"` // 分类排序值
}

type UpdatePasswordRequest struct {
	OldPassword string `json:"oldPassword"` // 旧密码
	NewPassword string `json:"newPassword"` // 新密码
}

type UpdatePostRequest struct {
	Id          int64  `path:"id"`                   // 资源 ID
	Title       string `json:"title"`                // 文章标题
	Slug        string `json:"slug"`                 // 文章别名
	Summary     string `json:"summary"`              // 文章摘要
	Content     string `json:"content"`              // 文章正文
	Cover       string `json:"cover"`                // 封面图片地址
	Status      string `json:"status"`               // 文章状态
	CategoryId  int64  `json:"categoryId"`           // 分类 ID
	PublishedAt int64  `json:"publishedAt,optional"` // 发布时间
}

type UpdateProfileRequest struct {
	DisplayName string `json:"displayName"` // 显示名称
	Avatar      string `json:"avatar"`      // 头像地址
	Bio         string `json:"bio"`         // 个人简介
	Email       string `json:"email"`       // 邮箱地址
	Website     string `json:"website"`     // 个人网站地址
	Github      string `json:"github"`      // GitHub 主页地址
}

type UploadImageRequest struct {
	Filename    string `json:"filename"`    // 图片文件名
	ContentType string `json:"contentType"` // 图片 MIME 类型
	Content     []byte `json:"content"`     // 图片二进制内容
}

type UploadImageResponse struct {
	Url string `json:"url"` // 图片访问地址
}

type UserResponse struct {
	Id          int64  `json:"id"`          // 资源 ID
	Username    string `json:"username"`    // 登录用户名
	DisplayName string `json:"displayName"` // 显示名称
	Avatar      string `json:"avatar"`      // 头像地址
	Bio         string `json:"bio"`         // 个人简介
	Email       string `json:"email"`       // 邮箱地址
	Website     string `json:"website"`     // 个人网站地址
	Github      string `json:"github"`      // GitHub 主页地址
}
