// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreatePostRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreatePostResponse struct {
	Id int64 `json:"id"`
}

type DeletePostRequest struct {
	Id int64 `json:"id"`
}

type DeletePostResponse struct {
}

type GetPostRequest struct {
	Id int64 `json:"id"`
}

type GetPostResponse struct {
	Id        int64  `json:"id"`
	UserId    int64  `json:"userId"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type ListPostsRequest struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type ListPostsResponse struct {
	Total int64      `json:"total"`
	Posts []PostItem `json:"posts"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type PostItem struct {
	Id        int64  `json:"id"`
	UserId    int64  `json:"userId"`
	Title     string `json:"title"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	UserId int64 `json:"userId"`
}

type UpdatePostRequest struct {
	Id      int64  `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UpdatePostResponse struct {
}

type UserResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
