// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	blogAdmin "myblog-api/internal/handler/blogAdmin"
	blogPublic "myblog-api/internal/handler/blogPublic"
	user "myblog-api/internal/handler/user"
	userAdmin "myblog-api/internal/handler/userAdmin"
	userAuth "myblog-api/internal/handler/userAuth"
	"myblog-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.BlogRateLimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/admin/categories",
					Handler: blogAdmin.CreateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/categories/:id/delete",
					Handler: blogAdmin.DeleteCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/categories/:id/update",
					Handler: blogAdmin.UpdateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/posts",
					Handler: blogAdmin.CreatePostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/posts/:id",
					Handler: blogAdmin.GetPostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/posts/:id/delete",
					Handler: blogAdmin.DeletePostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/posts/:id/update",
					Handler: blogAdmin.UpdatePostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/posts/list",
					Handler: blogAdmin.ListPostsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UploadRateLimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/admin/images",
					Handler: blogAdmin.UploadImageHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.BlogRateLimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/categories",
					Handler: blogPublic.ListCategoriesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/posts",
					Handler: blogPublic.ListPostsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/posts/:id",
					Handler: blogPublic.GetPostHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserRateLimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/profile",
					Handler: user.GetProfileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserRateLimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/admin/password/update",
					Handler: userAdmin.UpdatePasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/profile",
					Handler: userAdmin.GetMeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/profile/update",
					Handler: userAdmin.UpdateProfileHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LoginRateLimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/auth/login",
					Handler: userAuth.LoginHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
