// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: blog.proto

package blogclient

import (
	"context"

	"blog-rpc/pb/blog"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminPostItem           = blog.AdminPostItem
	AdminPostResponse       = blog.AdminPostResponse
	CategoryItem            = blog.CategoryItem
	CreateCategoryRequest   = blog.CreateCategoryRequest
	CreateCategoryResponse  = blog.CreateCategoryResponse
	CreatePostRequest       = blog.CreatePostRequest
	CreatePostResponse      = blog.CreatePostResponse
	DeleteCategoryRequest   = blog.DeleteCategoryRequest
	DeletePostRequest       = blog.DeletePostRequest
	Empty                   = blog.Empty
	EmptyResponse           = blog.EmptyResponse
	GetPostRequest          = blog.GetPostRequest
	ListAdminPostsResponse  = blog.ListAdminPostsResponse
	ListCategoriesResponse  = blog.ListCategoriesResponse
	ListPostsRequest        = blog.ListPostsRequest
	ListPublicPostsResponse = blog.ListPublicPostsResponse
	PublicPostItem          = blog.PublicPostItem
	PublicPostResponse      = blog.PublicPostResponse
	UpdateCategoryRequest   = blog.UpdateCategoryRequest
	UpdatePostRequest       = blog.UpdatePostRequest
	UploadImageRequest      = blog.UploadImageRequest
	UploadImageResponse     = blog.UploadImageResponse

	Blog interface {
		ListPublicPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPublicPostsResponse, error)
		GetPublicPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*PublicPostResponse, error)
		ListCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
		ListAdminPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListAdminPostsResponse, error)
		GetAdminPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*AdminPostResponse, error)
		CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
		UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
		UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageResponse, error)
	}

	defaultBlog struct {
		cli zrpc.Client
	}
)

func NewBlog(cli zrpc.Client) Blog {
	return &defaultBlog{
		cli: cli,
	}
}

func (m *defaultBlog) ListPublicPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPublicPostsResponse, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.ListPublicPosts(ctx, in, opts...)
}

func (m *defaultBlog) GetPublicPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*PublicPostResponse, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.GetPublicPost(ctx, in, opts...)
}

func (m *defaultBlog) ListCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.ListCategories(ctx, in, opts...)
}

func (m *defaultBlog) ListAdminPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListAdminPostsResponse, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.ListAdminPosts(ctx, in, opts...)
}

func (m *defaultBlog) GetAdminPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*AdminPostResponse, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.GetAdminPost(ctx, in, opts...)
}

func (m *defaultBlog) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

func (m *defaultBlog) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}

func (m *defaultBlog) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

func (m *defaultBlog) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.CreateCategory(ctx, in, opts...)
}

func (m *defaultBlog) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.UpdateCategory(ctx, in, opts...)
}

func (m *defaultBlog) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.DeleteCategory(ctx, in, opts...)
}

func (m *defaultBlog) UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageResponse, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.UploadImage(ctx, in, opts...)
}
