syntax = "proto3";

package user;

option go_package = "./user";

service User {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc GetProfile(Empty) returns (ProfileResponse);
  rpc GetMe(GetMeRequest) returns (UserResponse);
  rpc UpdateProfile(UpdateProfileRequest) returns (EmptyResponse);
  rpc UpdatePassword(UpdatePasswordRequest) returns (EmptyResponse);
}

message Empty {}

message EmptyResponse {}

message LoginRequest {
  string username = 1;
  string password = 2;
}

message LoginResponse {
  int64 user_id = 1;
  string username = 2;
}

message GetMeRequest {
  int64 user_id = 1;
}

message ProfileResponse {
  int64 id = 1;
  string username = 2;
  string display_name = 3;
  string avatar = 4;
  string bio = 5;
  string email = 6;
  string website = 7;
  string github = 8;
}

message UserResponse {
  int64 id = 1;
  string username = 2;
  string display_name = 3;
  string avatar = 4;
  string bio = 5;
  string email = 6;
  string website = 7;
  string github = 8;
}

message UpdateProfileRequest {
  int64 user_id = 1;
  string display_name = 2;
  string avatar = 3;
  string bio = 4;
  string email = 5;
  string website = 6;
  string github = 7;
}

message UpdatePasswordRequest {
  int64 user_id = 1;
  string old_password = 2;
  string new_password = 3;
}
